services:
  postgres:
    image: postgres:16
    container_name: med-scheduler-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: medscheduler_local
    ports:
      - "5432:5432"
    volumes:
      - med-scheduler-postgres-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d medscheduler_local"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  med-scheduler-postgres-data:
